<?php

namespace TestFormStepBundle\Repository;

/**
 * ChoixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Choix1Repository extends \Doctrine\ORM\EntityRepository
{
}
