<?php

namespace TestFormStepBundle\Repository;

/**
 * DomaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Etape1Repository extends \Doctrine\ORM\EntityRepository
{
}
