services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    memcached:
        class: Memcached
        calls:
            - [ addServers, ['%memcache_hosts%'] ]


    doctrine.cache.memcached:
        class: Doctrine\Common\Cache\MemcachedCache
        calls:
            - [ setMemcached, [ '@memcached' ] ]